### ISSUE TITLE
Understand templating system

### ISSUE THREAD

**Issue by mroswell** [mroswell/list-N#12]
/usr/local/Cellar/datasette/0.55/libexec/lib/python3.9/site-packages/datasette/templates

permissions_debug.html
messages_debug.html
**index.html**
patterns.html
_codemirror_foot.html
base.html
**_table.html**
**row.html**
**database.html**
**table.html**
_close_open_menus.html
_description_source_license.html
allow_debug.html
**query.html**
show_json.html
logout.html
error.html
_codemirror.html
_footer.html

**Comment by mroswell** [comment]
from: https://docs.datasette.io/en/0.40/custom_templates.html#custom-templates

Index page (/):
    index.html

Database page (/mydatabase):
    database-mydatabase.html
    database.html

Custom query page (/mydatabase?sql=...):
    query-mydatabase.html
    query.html

Canned query page (/mydatabase/canned-query):
    query-mydatabase-canned-query.html
    query-mydatabase.html
    query.html

Table page (/mydatabase/mytable):
    table-mydatabase-mytable.html
    table.html

Row page (/mydatabase/mytable/id):
    row-mydatabase-mytable.html
    row.html

Table of rows and columns include on table page:
    _table-table-mydatabase-mytable.html
    _table-mydatabase-mytable.html
    _table.html

Table of rows and columns include on row page:
    _table-row-mydatabase-mytable.html
    _table-mydatabase-mytable.html
    _table.html

**Comment by mroswell** [comment]
Get a better handle on block vs. extends vs. include
https://riptutorial.com/django/example/32472/use-of----extends---------include----and----blocks---

**Comment by mroswell** [comment]
use of the underscore character: https://craftcms.stackexchange.com/questions/8962/routing-templates-thats-start-with-an-underscore

**Comment by mroswell** [comment]
human_filter_description_en (in cosmology) vs. human_description_en (default)?

**Comment by mroswell** [comment]
canned query vs. custom sql?

**Comment by mroswell** [comment]
|capitalize
|join(", ")
|length
|escape_css_string
|escape_sqlite
|length
|length==1
|length !=
|length > 9
| string()) or "-" 
|to_css_class
|round(3)
|tojson
|urlencode|safe
|safe

**Comment by mroswell** [comment]
from: https://jinja.palletsprojects.com/en/2.10.x/templates/

{% ... %} for Statements
{{ ... }} for Expressions to print to the template output
{# ... #} for Comments not included in the template output
\#  ... ## for Line Statements

See also: https://www.webforefront.com/django/usebuiltinjinjafilters.html

**Comment by simonw** [comment]
You can create a `templates/` folder and put `index.html` in that folder to replace the homepage. That's how https://datasette.io/ works - https://github.com/simonw/datasette.io/blob/main/templates/index.html

**Comment by mroswell** [comment]
Template inheritance and block content: https://www.youtube.com/watch?v=DxI4jnb5m1Q
Template control structures

**Comment by mroswell** [comment]
url_builder.py
```
from .utils import path_with_format, HASH_LENGTH, PrefixedUrlString
import urllib

class Urls:
    def __init__(self, ds):
        self.ds = ds

    def path(self, path, format=None):
        if not isinstance(path, PrefixedUrlString):
            if path.startswith("/"):
                path = path[1:]
            path = self.ds.setting("base_url") + path
        if format is not None:
            path = path_with_format(path=path, format=format)
        return PrefixedUrlString(path)

    def instance(self, format=None):
        return self.path("", format=format)

    def static(self, path):
        return self.path(f"-/static/{path}")

    def static_plugins(self, plugin, path):
        return self.path(f"-/static-plugins/{plugin}/{path}")

    def logout(self):
        return self.path("-/logout")

    def database(self, database, format=None):
        db = self.ds.databases[database]
        if self.ds.setting("hash_urls") and db.hash:
            path = self.path(
                f"{urllib.parse.quote(database)}-{db.hash[:HASH_LENGTH]}", format=format
            )
        else:
            path = self.path(urllib.parse.quote(database), format=format)
        return path

    def table(self, database, table, format=None):
        path = f"{self.database(database)}/{urllib.parse.quote_plus(table)}"
        if format is not None:
            path = path_with_format(path=path, format=format)
        return PrefixedUrlString(path)

    def query(self, database, query, format=None):
        path = f"{self.database(database)}/{urllib.parse.quote_plus(query)}"
        if format is not None:
            path = path_with_format(path=path, format=format)
        return PrefixedUrlString(path)

    def row(self, database, table, row_path, format=None):
            path = f"{self.table(database, table)}/{row_path}"
        if format is not None:
            path = path_with_format(path=path, format=format)
        return PrefixedUrlString(path)

    def row_blob(self, database, table, row_path, column):
        return self.table(database, table) + "/{}.blob?_blob_column={}".format(
            row_path, urllib.parse.quote_plus(column)
            ```

**Comment by mroswell** [comment]
Closing. Will move some of this to a wiki, eventually.
