### ISSUE TITLE
Figure out how to set starting page

### ISSUE THREAD

**Issue by mroswell** [mroswell/list-N#13]

**Comment by mroswell** [comment]
Probably should default to ListN table page. Need to figure out table-level metadata as well.

**Comment by mroswell** [comment]
Applied table-level metadata

**Comment by simonw** [comment]
See suggestion at https://github.com/mroswell/list-N/issues/12#issuecomment-808441124

**Comment by mroswell** [comment]
Too hard to move table page to the root. It's a good feature request for datasette. (https://github.com/simonw/datasette/issues/1284)

Switch to building shuffle.dev home page that points to the table page.

**Comment by mroswell** [comment]
Super-helpful support from Michael Belfrage. https://gist.github.com/mikez/f84bfa5edfa7212a604680233e2ecf8c
https://belfrage.net/share/screencast-2021-04-14T00-59-14.711683+02-00.mp4

**Comment by mroswell** [comment]
From here work on content. (Ideally-CMS-ify [#revisit], but too much work to figure out.)
