### ISSUE TITLE
figure out how to control the order of the columns

### ISSUE THREAD

**Issue by mroswell** [mroswell/list-N#6]

**Comment by mroswell** [comment]
This seems to be the default. 
```
select
  [Why on List N],
  [Registration number],
  [Company URL],
  [Formulation type],
  [Contact time],
  [Active ingredients],
  [Use site],
  Company,
  [Follow directions for this virus],
  [Date on List N],
  [Product name],
  ID,
  [Active ingredient],
  [Surface type]
from
  listN
order by
  ID
limit
  101
```

**Comment by simonw** [comment]
In `sqlite-utils` Python you can do that like this: https://sqlite-utils.datasette.io/en/stable/python-api.html?highlight=column%20order#custom-column-order-and-column-types

Or you can use this: https://sqlite-utils.datasette.io/en/stable/python-api.html?highlight=column_order#transforming-a-table

**Comment by mroswell** [comment]
I see this in the documentation:
```
# Change column order
table.transform(column_order=("name", "age", "id")
```
I'll have to figure out where that belongs in the workflow.

**Comment by mroswell** [comment]
sqlite-utils transform listN.db listN \\
--column-order EPA_reg_num \\
--column-order Safer_or_Toxic \\
--column-order Active_ingredient \\
--column-order Product_name \\
--column-order Company \\
--column-order Use_site \\
--column-order Surface_type \\
--column-order Contact_time \\
--column-order Formulation_type \\
--column-order Follow_directions_for_this_virus \\
--column-order Date_on_List_N \\
--column-order Why_on_List_N \\
--column-order ID

Will need to figure out how to incorporate this into the GitHub action
